### ISSUE TITLE
Question: How to verify that changes are based on code identical to upstream release?

### ISSUE THREAD

**Issue by kabalin** [trejan/VMG3925-B10B#1]
It might be useful to somehow demonstrate (perhaps an instruction explaining how to get an original firmware codebase?) that https://github.com/trejan/VMG3925-B10B/commit/2260d8ca8d07802c9f7054acb3ac3a78320946b1 is identical to upstream version V5.13(AAVF.11)C0? 

Thanks for the great work in fact! I need this jumbo frames support in bridge mode.

**Comment by kabalin** [comment]
Well, I found the answer myself. https://github.com/trejan/VMG3925-B10B/commit/2260d8ca8d07802c9f7054acb3ac3a78320946b1 is indeed contains clean upstream release.

Just in case someone wants to check this independently. First, one need to request a firmware using the form https://www.zyxel.com/us/en/form/gpl_oss_form.shtml

Once you got a response from Zyxel, download firmware archive using the link they provided, unpack it and create a new git repo on a clean copy of upstream source code. Then add remote repo pointing to this repository and cherry-pick first commit in this repo (https://github.com/trejan/VMG3925-B10B/commit/2260d8ca8d07802c9f7054acb3ac3a78320946b1). Here is an output:
```
~/Downloads/firmware/vmg3926_release> git init
Initialized empty Git repository in /home/ruslan/Downloads/firmware/vmg3926_release/.git/
~/Downloads/firmware/vmg3926_release> git add .
~/Downloads/firmware/vmg3926_release> git commit -m "Upsream release of V513AAVF11C0 for Zyxel VMG3925-B10B"
....
vmg3926_release:master> git remote add trejan https://github.com/trejan/VMG3925-B10B.git
vmg3926_release:master> git fetch trejan 
warning: no common commits
remote: Enumerating objects: 7044, done.
remote: Counting objects: 100% (7044/7044), done.
remote: Compressing objects: 100% (5518/5518), done.
remote: Total 7044 (delta 1186), reused 7036 (delta 1178), pack-reused 0
Receiving objects: 100% (7044/7044), 327.10 MiB | 31.14 MiB/s, done.
Resolving deltas: 100% (1186/1186), done.
From https://github.com/trejan/VMG3925-B10B
 * [new branch]      master     -> trejan/master
 * [new tag]         V5.13(AAVF.11)C0-BabyJumbo-Supervisor -> V5.13(AAVF.11)C0-BabyJumbo-Supervisor
 * [new tag]         V5.13(AAVF.11)C0-Jumbo                -> V5.13(AAVF.11)C0-Jumbo
vmg3926_release:master> git cherry-pick -n 2260d8ca8d07802c9f7054acb3ac3a78320946b1
vmg3926_release:master> git status 
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   README.md

vmg3926_release:master>
```
The above suggests that the only difference to upstream repo is README.md file presence.

**Comment by trejan** [comment]
It is great you've managed to verify the source. You're right. I should say how to get the source from Zyxel. I'll update README.md with some notes about that.

If you're only interested in jumbo frames then it is just the 3 line change to [target/linux/brcm963xx/bcmsdk-416L05-AAVF-config-3.4](https://github.com/trejan/VMG3925-B10B/commit/1b41dc24b9e382dd8e12d5367dec229ab0d82e22#diff-8d4e067f149e0eb07ed3eff03f6dbc25) It is strange that Zyxel don't enable it since Broadcom officially support it in this newer version of their SDK used with the VMG3925-B10B. Older versions required a minor change to the code.
