### ISSUE TITLE
license issue

### ISSUE THREAD

**Issue by mandywu0212** [trejan/VMG3925-B10B#2]
Hi @trejan ,

I am Pei-Fen Wu that work for ZYXEL.
Due license issue, we hope and need your help to remove some files from this repositories.
Could you kindly contact with me by mail for more discuss ?
My mail address is Peifen.wu@zyxel.com.tw
I am looking forward to your mail.

BRs,
Pei-Fen

**Comment by trejan** [comment]
Dealt with this via email. Closing.
